### ISSUE TITLE
Looks like LinkedIn doesn't want people without LinkedIn account get the user profile even if it's public

### ISSUE THREAD

**Issue by fkztw** [M157q/linkedin2md#8]
`webkit_server.InvalidResponseError: {"class":"InvalidResponseError","message":"Unable to load URL: https://www.linkedin.com/in/shunyi because of error loading https://www.linkedin.com/in/shunyi: Request denied"}`

Still can get the user profile when use Chromium with incognito mode at the first time. Refresh the page will be redirected to the login page. It looks like there's still a chance to get the public user profile without using LinkedIn API, just need to find a tricky way to deal with it.

**Comment by fkztw** [comment]
Now even using chromium with incognito mode cannot get the user profile at the first time.

**Comment by fkztw** [comment]
It looks like we have to login before grabbing anyone's LinkedIn profile.

**Comment by kenshinji** [comment]
yeah, I ran into the same issue, did you fix it?

**Comment by fkztw** [comment]
@kenshinji Nope. It looks like we have to login with username and password or just use the LinkedIn API.

**Comment by kenshinji** [comment]
@M157q so there is no entry for inputting username and password to login for now?

**Comment by fkztw** [comment]
I think I will write a new feature which make user save LinkedIn account and password in the config file then use them to login LinkedIn and we'll be good.

**Comment by kenshinji** [comment]
sounds great!

**Comment by fkztw** [comment]
I won't maintain this project anymore.
Here are the reasons: https://github.com/M157q/linkedin2md/commit/297f1c3ca0c2d40add957fd735b8bf825268a38b
